#!/usr/bin/env bash
# run_doe_sensitivity.sh — DOE-style step-size sensitivity experiment
#
# Factors:
#   A: Base step length  {0.025, 0.0125, 0.00625}
#   B: Resolver          {off, on}
#   C: Step-conv telem   {off, on}
#
# C=on is suppressed automatically when B=on (resolver + step-conv is invalid).
#
# Usage:
#   bash scripts/run_doe_sensitivity.sh [--output <dir>]
#
# Outputs: <output>/doe_<timestamp>/
#   per-cell folders: step_<sl>/off|telemetry_on|resolver_on|sconv_on/
#   DOE_summary.csv, DOE_summary.md (generated by doe_band_analysis.py)
#
# Prerequisites: GODOT_BIN set, .venv/bin/python3 with PIL/numpy/scipy/cv2

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCENE="${DOE_SCENE:-res://test-domain-resolver-stress.tscn}"
FIXTURE="domain_resolver_stress"
FRAMES=90
WARMUP=5
FILM_W=320
FILM_H=180
FILM_SCALE=1.0
GODOT_BIN="${GODOT_BIN:-$ROOT/scripts/godot_local.sh}"
PYTHON="${ROOT}/.venv/bin/python3"
VENV_PYTHON="${ROOT}/.venv/bin/python3"

STEP_LENGTHS=("0.025" "0.0125" "0.00625")
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUTPUT_BASE="${ROOT}/output/doe_sensitivity"
OUTPUT_DIR="${OUTPUT_BASE}/${TIMESTAMP}"

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)       OUTPUT_DIR="$2";             shift 2 ;;
        --frames)       FRAMES="$2";                 shift 2 ;;
        --warmup)       WARMUP="$2";                 shift 2 ;;
        --step-lengths) IFS=',' read -ra STEP_LENGTHS <<< "$2"; shift 2 ;;
        *) echo "[doe] unknown arg: $1" >&2; exit 1 ;;
    esac
done

mkdir -p "$OUTPUT_DIR"
LOG="${OUTPUT_DIR}/doe_run.log"
exec > >(tee -a "$LOG") 2>&1

echo "[doe] output=$OUTPUT_DIR"
echo "[doe] step_lengths=${STEP_LENGTHS[*]}"
echo "[doe] frames=$FRAMES warmup=$WARMUP res=${FILM_W}x${FILM_H}"

# Build first
echo "[doe] dotnet build"
dotnet build "$ROOT" 2>&1
echo "[doe] build done"

# ---- helper: run one Godot capture -------------------------------------------
# run_case <out_dir> <label> <step_len> <telemetry> <resolver> <step_conv>
run_case() {
    local case_dir="$1"
    local label="$2"
    local step_len="$3"
    local telemetry="$4"
    local resolver="$5"
    local step_conv="$6"

    mkdir -p "$case_dir"

    local stem="${FIXTURE}__${label}__sl${step_len}__baseline_prune_off__scheduler-baseline__targetms-1000__stride-2__runid-1"

    echo "[doe] run label=${label} sl=${step_len} telemetry=${telemetry} resolver=${resolver} sconv=${step_conv}"

    "$GODOT_BIN" --headless --path "$ROOT" --scene "$SCENE" -- \
        --render-test \
        --domain-audit-quick \
        "--render-test-fixture=$FIXTURE" \
        --render-test-capture=1 \
        "--render-test-capture-dir=$case_dir" \
        "--render-test-capture-mode=$label" \
        "--render-test-frames=$FRAMES" \
        "--render-test-warmup=$WARMUP" \
        "--render-test-film-width=$FILM_W" \
        "--render-test-film-height=$FILM_H" \
        "--render-test-film-scale=$FILM_SCALE" \
        --render-test-camera-fixed=1 \
        "--render-test-step-length=$step_len" \
        "--enable-domain-telemetry=$telemetry" \
        "--enable-domain-aware-first-hit-resolver=$resolver" \
        "--enable-step-convergence-telemetry=$step_conv" \
        > "$case_dir/run.log" 2>&1

    local exit_code=$?
    local effective=0
    local note=""
    if [[ $exit_code -eq 0 ]]; then
        note="clean_exit"
    elif [[ $exit_code -eq 134 ]] || grep -q "\[RenderTestRunner\]\[ExitCode\] forced=0 reason=harness_success" "$case_dir/run.log" 2>/dev/null; then
        note="godot_shutdown_abort_after_harness_success"
        effective=0
    else
        effective=$exit_code
        note="error"
    fi
    echo "$effective" > "$case_dir/effective_status.txt"
    echo "$exit_code"  > "$case_dir/status.txt"
    echo "[doe] status label=${label} sl=${step_len} exit=${exit_code} effective=${effective}${note:+ note=${note}}"
    return $effective
}

# ---- main DOE loop -----------------------------------------------------------
all_cells=()   # for analysis script

for SL in "${STEP_LENGTHS[@]}"; do
    sl_dir="${OUTPUT_DIR}/step_${SL}"
    mkdir -p "$sl_dir"

    # -- OFF (no telemetry, no resolver, no step-conv) -------------------------
    off_dir="${sl_dir}/off"
    run_case "$off_dir" "off" "$SL" 0 0 0 || true

    # -- telemetry ON, resolver OFF, step-conv OFF -----------------------------
    tel_dir="${sl_dir}/telemetry_on"
    run_case "$tel_dir" "telemetry_on" "$SL" 1 0 0 || true

    # -- telemetry ON, resolver OFF, step-conv ON ------------------------------
    sconv_dir="${sl_dir}/sconv_on"
    run_case "$sconv_dir" "sconv_on" "$SL" 1 0 1 || true

    # -- resolver ON (implicitly telemetry ON, step-conv OFF) ------------------
    res_dir="${sl_dir}/resolver_on"
    run_case "$res_dir" "resolver_on" "$SL" 1 1 0 || true

    # beauty hash comparison: off vs telemetry
    off_png="${off_dir}/$(ls "$off_dir"/*.png 2>/dev/null | grep -v '\.step_convergence\|\.step_sensitivity\|\.precision_required\|\.boundary\|\.domain\|\.selection\|\.normal' | head -1 | xargs basename 2>/dev/null)" 2>/dev/null || off_png=""
    tel_png="${tel_dir}/$(ls "$tel_dir"/*.png 2>/dev/null | grep -v '\.step_convergence\|\.step_sensitivity\|\.precision_required\|\.boundary\|\.domain\|\.selection\|\.normal' | head -1 | xargs basename 2>/dev/null)" 2>/dev/null || tel_png=""

    # Use python for hash (more portable)
    if [[ -f "${off_dir}/${off_png##*/}" && -f "${tel_dir}/${tel_png##*/}" ]]; then
        off_hash=$(sha256sum "${off_dir}/${off_png##*/}" | cut -c1-64)
        tel_hash=$(sha256sum "${tel_dir}/${tel_png##*/}" | cut -c1-64)
        if [[ "$off_hash" == "$tel_hash" ]]; then
            echo "[doe] beauty_off_vs_tel sl=${SL} MATCH (passive ok)"
        else
            echo "[doe] beauty_off_vs_tel sl=${SL} DIFFERENT (pre-existing structural difference)"
        fi
    fi

    all_cells+=("$SL")
done

echo "[doe] all step levels complete: ${all_cells[*]}"

# ---- run analysis ------------------------------------------------------------
echo "[doe] running doe_band_analysis.py"
"$VENV_PYTHON" "${ROOT}/tools/doe_band_analysis.py" "$OUTPUT_DIR" 2>&1

echo "[doe] complete output=$OUTPUT_DIR"
